
var loadBsdiff = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var e=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,ea="function"==typeof importScripts,k="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node;if(k){const {createRequire:a}=await import("module");var require=a(import.meta.url)}var fa=Object.assign({},e),ia=[],ja="./this.program",ka=(a,b)=>{throw b;},q="",la,ma;
if(k){var fs=require("fs"),na=require("path");q=require("url").fileURLToPath(new URL("./",import.meta.url));ma=a=>{a=oa(a)?new URL(a):na.normalize(a);return fs.readFileSync(a)};la=a=>{a=oa(a)?new URL(a):na.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,f)=>{d?c(d):b(f.buffer)})})};!e.thisProgram&&1<process.argv.length&&(ja=process.argv[1].replace(/\\/g,"/"));ia=process.argv.slice(2);ka=(a,b)=>{process.exitCode=a;throw b;}}else if(da||ea)ea?q=self.location.href:"undefined"!=
typeof document&&document.currentScript&&(q=document.currentScript.src),_scriptName&&(q=_scriptName),q.startsWith("blob:")?q="":q=q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1),ea&&(ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=a=>oa(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};
d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var pa=e.print||console.log.bind(console),u=e.printErr||console.error.bind(console);Object.assign(e,fa);fa=null;var qa,ra=!1,v,w,A,sa,B,E,ta;
function ua(){var a=qa.buffer;e.HEAP8=w=new Int8Array(a);e.HEAP16=sa=new Int16Array(a);e.HEAPU8=A=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAP32=B=new Int32Array(a);e.HEAPU32=E=new Uint32Array(a);e.HEAPF32=new Float32Array(a);e.HEAPF64=new Float64Array(a);e.HEAP64=ta=new BigInt64Array(a);e.HEAPU64=new BigUint64Array(a)}var va=[],wa=[],xa=[],ya=[],F=0,za=null,Aa=null;function Ba(){F--;if(0==F&&(null!==za&&(clearInterval(za),za=null),Aa)){var a=Aa;Aa=null;a()}}
function Ca(a){a="Aborted("+a+")";u(a);ra=!0;v=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Da=a=>a.startsWith("data:application/octet-stream;base64,"),oa=a=>a.startsWith("file://"),Ea;function Fa(a){return la(a).then(b=>new Uint8Array(b),()=>{if(ma)var b=ma(a);else throw"both async and sync fetching of the wasm failed";return b})}
function Ga(a,b,c){return Fa(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{u(`failed to asynchronously prepare wasm: ${d}`);Ca(d)})}function Ha(a,b){var c=Ea;return"function"!=typeof WebAssembly.instantiateStreaming||Da(c)||oa(c)||k||"function"!=typeof fetch?Ga(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){u(`wasm streaming compile failed: ${f}`);u("falling back to ArrayBuffer instantiation");return Ga(c,a,b)}))}
function Ia(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Ja=a=>{for(;0<a.length;)a.shift()(e)};function G(){var a=B[+Ka>>2];Ka+=4;return a}
var La=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},H=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=La(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ma=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},I=a=>{if("/"===
a)return"/";a=H(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Na=(...a)=>H(a.join("/")),Oa=(a,b)=>H(a+"/"+b),Pa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(k)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}Ca("initRandomDevice")},Qa=a=>(Qa=Pa())(a),K=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=
0<=d?a[d]:J.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=La(b.split("/").filter(f=>!!f),!c).join("/");return(c?"/":"")+b||"."},Ra=(a,b)=>{function c(h){for(var l=0;l<h.length&&""===h[l];l++);for(var p=h.length-1;0<=p&&""===h[p];p--);return l>p?[]:h.slice(l,p-l+1)}a=K(a).substr(1);b=K(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=
g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")},Sa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,L=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Sa)return Sa.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|
f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Ta=[],Ua=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Va=(a,b,c,d)=>{if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|
h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f};function Wa(a){var b=Array(Ua(a)+1);a=Va(a,b,0,b.length);b.length=a;return b}var Xa=[];function Ya(a,b){Xa[a]={input:[],output:[],P:b};Za(a,$a)}
var $a={open(a){var b=Xa[a.node.rdev];if(!b)throw new J.s(43);a.tty=b;a.seekable=!1},close(a){a.tty.P.fsync(a.tty)},fsync(a){a.tty.P.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.P.Ha)throw new J.s(60);for(var f=0,g=0;g<d;g++){try{var h=a.tty.P.Ha(a.tty)}catch(l){throw new J.s(29);}if(void 0===h&&0===f)throw new J.s(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write(a,b,c,d){if(!a.tty||!a.tty.P.ta)throw new J.s(60);try{for(var f=0;f<d;f++)a.tty.P.ta(a.tty,
b[c+f])}catch(g){throw new J.s(29);}d&&(a.node.timestamp=Date.now());return f}},ab={Ha(){a:{if(!Ta.length){var a=null;if(k){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(f){if(f.toString().includes("EOF"))c=0;else throw f;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ta=Wa(a)}a=Ta.shift()}return a},ta(a,b){null===b||10===b?(pa(L(a.output,
0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(pa(L(a.output,0)),a.output=[])},Ya(){return{hb:25856,jb:5,gb:191,ib:35387,fb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Za(){return 0},$a(){return[24,80]}},bb={ta(a,b){null===b||10===b?(u(L(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(u(L(a.output,0)),a.output=[])}},db=a=>{a=65536*Math.ceil(a/65536);var b=cb(65536,a);b?(A.fill(0,b,b+a),a=b):
a=0;return a};function eb(a,b){var c=a.B?a.B.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.B,a.B=new Uint8Array(b),0<a.D&&a.B.set(c.subarray(0,a.D),0))}
var M={O:null,C(){return M.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||J.isFIFO(c))throw new J.s(63);M.O||(M.O={dir:{node:{G:M.v.G,F:M.v.F,lookup:M.v.lookup,I:M.v.I,rename:M.v.rename,unlink:M.v.unlink,rmdir:M.v.rmdir,readdir:M.v.readdir,symlink:M.v.symlink},stream:{H:M.A.H}},file:{node:{G:M.v.G,F:M.v.F},stream:{H:M.A.H,read:M.A.read,write:M.A.write,Y:M.A.Y,S:M.A.S,U:M.A.U}},link:{node:{G:M.v.G,F:M.v.F,readlink:M.v.readlink},stream:{}},Ca:{node:{G:M.v.G,F:M.v.F},stream:J.Ra}});
c=J.createNode(a,b,c,d);N(c.mode)?(c.v=M.O.dir.node,c.A=M.O.dir.stream,c.B={}):J.isFile(c.mode)?(c.v=M.O.file.node,c.A=M.O.file.stream,c.D=0,c.B=null):40960===(c.mode&61440)?(c.v=M.O.link.node,c.A=M.O.link.stream):8192===(c.mode&61440)&&(c.v=M.O.Ca.node,c.A=M.O.Ca.stream);c.timestamp=Date.now();a&&(a.B[b]=c,a.timestamp=c.timestamp);return c},nb(a){return a.B?a.B.subarray?a.B.subarray(0,a.D):new Uint8Array(a.B):new Uint8Array(0)},v:{G(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=
a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N(a.mode)?b.size=4096:J.isFile(a.mode)?b.size=a.D:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.R=4096;b.blocks=Math.ceil(b.size/b.R);return b},F(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.D!=b))if(0==b)a.B=null,a.D=0;else{var c=a.B;a.B=new Uint8Array(b);c&&a.B.set(c.subarray(0,Math.min(b,
a.D)));a.D=b}},lookup(){throw J.ka[44];},I(a,b,c,d){return M.createNode(a,b,c,d)},rename(a,b,c){if(N(a.mode)){try{var d=O(b,c)}catch(g){}if(d)for(var f in d.B)throw new J.s(55);}delete a.parent.B[a.name];a.parent.timestamp=Date.now();a.name=c;b.B[c]=a;b.timestamp=a.parent.timestamp},unlink(a,b){delete a.B[b];a.timestamp=Date.now()},rmdir(a,b){var c=O(a,b),d;for(d in c.B)throw new J.s(55);delete a.B[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.B))b.push(c);return b},
symlink(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new J.s(28);return a.link}},A:{read(a,b,c,d,f){var g=a.node.B;if(f>=a.node.D)return 0;a=Math.min(a.node.D-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write(a,b,c,d,f,g){b.buffer===w.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.B||a.B.subarray)){if(g)return a.B=b.subarray(c,c+d),a.D=d;if(0===a.D&&0===f)return a.B=
b.slice(c,c+d),a.D=d;if(f+d<=a.D)return a.B.set(b.subarray(c,c+d),f),d}eb(a,f+d);if(a.B.subarray&&b.subarray)a.B.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.B[f+g]=b[c+g];a.D=Math.max(a.D,f+d);return d},H(a,b,c){1===c?b+=a.position:2===c&&J.isFile(a.node.mode)&&(b+=a.node.D);if(0>b)throw new J.s(28);return b},Y(a,b,c){eb(a.node,b+c);a.node.D=Math.max(a.node.D,b+c)},S(a,b,c,d,f){if(!J.isFile(a.node.mode))throw new J.s(43);a=a.node.B;if(f&2||!a||a.buffer!==w.buffer){d=!0;f=db(b);if(!f)throw new J.s(48);
if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);w.set(a,f)}}else d=!1,f=a.byteOffset;return{sa:f,ga:d}},U(a,b,c,d){M.A.write(a,b,0,d,c,!1);return 0}}},fb=(a,b,c)=>{var d=`al ${a}`;la(a).then(f=>{b(new Uint8Array(f));d&&Ba(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&F++},gb=[],hb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.na();var f=!1;gb.forEach(g=>{!f&&g.canHandle(b)&&(g.handle(a,b,c,d),f=!0)});return f},ib=(a,b,c,d,f,
g,h,l,p,n)=>{function r(x){function y(z){n?.();l||J.ha(a,b,z,d,f,p);g?.();Ba(t)}hb(x,m,y,()=>{h?.();Ba(t)})||y(x)}var m=b?K(H(a+"/"+b)):a,t=`cp ${m}`;F++;"string"==typeof c?fb(c,r,h):r(c)},jb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},kb={EPERM:63,ENOENT:44,ESRCH:71,EINTR:27,EIO:29,ENXIO:60,E2BIG:1,ENOEXEC:45,EBADF:8,ECHILD:12,EAGAIN:6,EWOULDBLOCK:6,ENOMEM:48,EACCES:2,EFAULT:21,ENOTBLK:105,EBUSY:10,EEXIST:20,EXDEV:75,ENODEV:43,ENOTDIR:54,EISDIR:31,EINVAL:28,ENFILE:41,EMFILE:33,ENOTTY:59,ETXTBSY:74,
EFBIG:22,ENOSPC:51,ESPIPE:70,EROFS:69,EMLINK:34,EPIPE:64,EDOM:18,ERANGE:68,ENOMSG:49,EIDRM:24,ECHRNG:106,EL2NSYNC:156,EL3HLT:107,EL3RST:108,ELNRNG:109,EUNATCH:110,ENOCSI:111,EL2HLT:112,EDEADLK:16,ENOLCK:46,EBADE:113,EBADR:114,EXFULL:115,ENOANO:104,EBADRQC:103,EBADSLT:102,EDEADLOCK:16,EBFONT:101,ENOSTR:100,ENODATA:116,ETIME:117,ENOSR:118,ENONET:119,ENOPKG:120,EREMOTE:121,ENOLINK:47,EADV:122,ESRMNT:123,ECOMM:124,EPROTO:65,EMULTIHOP:36,EDOTDOT:125,EBADMSG:9,ENOTUNIQ:126,EBADFD:127,EREMCHG:128,ELIBACC:129,
ELIBBAD:130,ELIBSCN:131,ELIBMAX:132,ELIBEXEC:133,ENOSYS:52,ENOTEMPTY:55,ENAMETOOLONG:37,ELOOP:32,EOPNOTSUPP:138,EPFNOSUPPORT:139,ECONNRESET:15,ENOBUFS:42,EAFNOSUPPORT:5,EPROTOTYPE:67,ENOTSOCK:57,ENOPROTOOPT:50,ESHUTDOWN:140,ECONNREFUSED:14,EADDRINUSE:3,ECONNABORTED:13,ENETUNREACH:40,ENETDOWN:38,ETIMEDOUT:73,EHOSTDOWN:142,EHOSTUNREACH:23,EINPROGRESS:26,EALREADY:7,EDESTADDRREQ:17,EMSGSIZE:35,EPROTONOSUPPORT:66,ESOCKTNOSUPPORT:137,EADDRNOTAVAIL:4,ENETRESET:39,EISCONN:30,ENOTCONN:53,ETOOMANYREFS:141,
EUSERS:136,EDQUOT:19,ESTALE:72,ENOTSUP:138,ENOMEDIUM:148,EILSEQ:25,EOVERFLOW:61,ECANCELED:11,ENOTRECOVERABLE:56,EOWNERDEAD:62,ESTRPIPE:135};function P(a){try{return a()}catch(b){if(!b.code)throw b;if("UNKNOWN"===b.code)throw new J.s(28);throw new J.s(kb[b.code]);}}function lb(a){var b;return P(()=>{b=fs.lstatSync(a);Q.qa&&(b.mode|=(b.mode&292)>>2);return b.mode})}function R(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.C.aa.root);b.reverse();return Na(...b)}
var Q={qa:!1,xa(){Q.qa=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);Q.Ga={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,256:a.O_NOCTTY,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY,131072:a.O_NOFOLLOW}},C(a){return Q.createNode(null,"/",lb(a.aa.root),0)},createNode(a,b,c){if(!N(c)&&!J.isFile(c)&&40960!==(c&61440))throw new J.s(28);a=J.createNode(a,b,c);a.v=Q.v;a.A=Q.A;return a},v:{G(a){var b=R(a),c;P(()=>c=fs.lstatSync(b));Q.qa&&(c.R||(c.R=4096),
c.blocks||(c.blocks=(c.size+c.R-1)/c.R|0),c.mode|=(c.mode&292)>>2);return{dev:c.dev,ino:c.ino,mode:c.mode,nlink:c.nlink,uid:c.uid,gid:c.gid,rdev:c.rdev,size:c.size,atime:c.atime,mtime:c.mtime,ctime:c.ctime,R:c.R,blocks:c.blocks}},F(a,b){var c=R(a);P(()=>{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode);void 0!==b.size&&fs.truncateSync(c,b.size)})},lookup(a,b){var c=R(a);c=H(c+"/"+b);c=lb(c);return Q.createNode(a,b,c)},I(a,b,c,d){var f=Q.createNode(a,b,c,d),g=R(f);P(()=>{N(f.mode)?fs.mkdirSync(g,
f.mode):fs.writeFileSync(g,"",{mode:f.mode})});return f},rename(a,b,c){var d=R(a),f=Oa(R(b),c);P(()=>fs.renameSync(d,f));a.name=c},unlink(a,b){var c=Oa(R(a),b);P(()=>fs.unlinkSync(c))},rmdir(a,b){var c=Oa(R(a),b);P(()=>fs.rmdirSync(c))},readdir(a){var b=R(a);return P(()=>fs.readdirSync(b))},symlink(a,b,c){var d=Oa(R(a),b);P(()=>fs.symlinkSync(c,d))},readlink(a){var b=R(a);return P(()=>fs.readlinkSync(b))}},A:{open(a){var b=R(a.node);P(()=>{if(J.isFile(a.node.mode)){a.W.Ka=1;var c=fs,d=c.openSync,
f=a.flags;f&=-2721793;var g=0,h;for(h in Q.Ga)f&h&&(g|=Q.Ga[h],f^=h);if(f)throw new J.s(28);a.$=d.call(c,b,g)}})},close(a){P(()=>{J.isFile(a.node.mode)&&a.$&&0===--a.W.Ka&&fs.closeSync(a.$)})},Ta(a){a.W.Ka++},read(a,b,c,d,f){return 0===d?0:P(()=>fs.readSync(a.$,new Int8Array(b.buffer,c,d),0,d,f))},write(a,b,c,d,f){return P(()=>fs.writeSync(a.$,new Int8Array(b.buffer,c,d),0,d,f))},H(a,b,c){var d=b;1===c?d+=a.position:2===c&&J.isFile(a.node.mode)&&P(()=>{d+=fs.fstatSync(a.$).size});if(0>d)throw new J.s(28);
return d},S(a,b,c){if(!J.isFile(a.node.mode))throw new J.s(43);var d=db(b);Q.A.read(a,w,d,b,c);return{sa:d,ga:!0}},U(a,b,c,d){Q.A.write(a,b,0,d,c,!1);return 0}}},S={fa:16895,X:33279,va:null,C(a){function b(g){g=g.split("/");for(var h=d,l=0;l<g.length-1;l++){var p=g.slice(0,l+1).join("/");let n,r;(n=f)[r=p]||(n[r]=S.createNode(h,g[l],S.fa,0));h=f[p]}return h}function c(g){g=g.split("/");return g[g.length-1]}ea||Ca();S.va||(S.va=new FileReaderSync);var d=S.createNode(null,"/",S.fa,0),f={};Array.prototype.forEach.call(a.aa.files||
[],function(g){S.createNode(b(g.name),c(g.name),S.X,0,g,g.lastModifiedDate)});(a.aa.blobs||[]).forEach(function(g){S.createNode(b(g.name),c(g.name),S.X,0,g.data)});(a.aa.packages||[]).forEach(function(g){g.metadata.files.forEach(function(h){var l=h.filename.substr(1);S.createNode(b(l),c(l),S.X,0,g.blob.slice(h.start,h.end))})});return d},createNode(a,b,c,d,f,g){d=J.createNode(a,b,c);d.mode=c;d.v=S.v;d.A=S.A;d.timestamp=(g||new Date).getTime();S.X!==S.fa||Ca();c===S.X?(d.size=f.size,d.B=f):(d.size=
4096,d.B={});a&&(a.B[b]=d);return d},v:{G(a){return{dev:1,ino:a.id,mode:a.mode,nlink:1,uid:0,gid:0,rdev:0,size:a.size,atime:new Date(a.timestamp),mtime:new Date(a.timestamp),ctime:new Date(a.timestamp),R:4096,blocks:Math.ceil(a.size/4096)}},F(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp)},lookup(){throw new J.s(44);},I(){throw new J.s(63);},rename(){throw new J.s(63);},unlink(){throw new J.s(63);},rmdir(){throw new J.s(63);},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.B))b.push(c);
return b},symlink(){throw new J.s(63);}},A:{read(a,b,c,d,f){if(f>=a.node.size)return 0;a=a.node.B.slice(f,f+d);d=S.va.readAsArrayBuffer(a);b.set(new Uint8Array(d),c);return a.size},write(){throw new J.s(29);},H(a,b,c){1===c?b+=a.position:2===c&&J.isFile(a.node.mode)&&(b+=a.node.size);if(0>b)throw new J.s(28);return b}}};function Za(a,b){J.Fa[a]={A:b}}function N(a){return 16384===(a&61440)}
function O(a,b){var c=N(a.mode)?(c=T(a,"x"))?c:a.v.lookup?0:2:54;if(c)throw new J.s(c);for(c=J.N[mb(a.id,b)];c;c=c.V){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return J.lookup(a,b)}
function U(a,b={}){a=K(a);if(!a)return{path:"",node:null};b=Object.assign({ja:!0,wa:0},b);if(8<b.wa)throw new J.s(32);a=a.split("/").filter(h=>!!h);for(var c=J.root,d="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;c=O(c,a[f]);d=H(d+"/"+a[f]);c.J&&(!g||g&&b.ja)&&(c=c.J.root);if(!g||b.M)for(g=0;40960===(c.mode&61440);)if(c=J.readlink(d),d=K(Ma(d),c),c=U(d,{wa:b.wa+1}).node,40<g++)throw new J.s(32);}return{path:d,node:c}}
function V(a){for(var b;;){if(J.Ia(a))return a=a.C.Ja,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function mb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%J.N.length}function nb(a){var b=mb(a.parent.id,a.name);a.V=J.N[b];J.N[b]=a}function ob(a){var b=mb(a.parent.id,a.name);if(J.N[b]===a)J.N[b]=a.V;else for(b=J.N[b];b;){if(b.V===a){b.V=a.V;break}b=b.V}}function pb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function T(a,b){if(J.ma)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function qb(a,b){try{return O(a,b),20}catch(c){}return T(a,"wx")}function rb(a,b,c){try{var d=O(a,b)}catch(f){return f.L}if(a=T(a,"wx"))return a;if(c){if(!N(d.mode))return 54;if(J.Ia(d)||V(d)===J.cwd())return 10}else if(N(d.mode))return 31;return 0}function W(a){a=J.Xa(a);if(!a)throw new J.s(8);return a}
function sb(a,b=-1){a=Object.assign(new J.Oa,a);if(-1==b)a:{for(b=0;b<=J.Pa;b++)if(!J.streams[b])break a;throw new J.s(33);}a.fd=b;return J.streams[b]=a}function tb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.Z)}return b}function ub(a,b,c){"undefined"==typeof c&&(c=b,b=438);return J.I(a,b|8192,c)}
function vb(){J.mkdir("/dev");Za(J.T(1,3),{read:()=>0,write:(d,f,g,h)=>h});ub("/dev/null",J.T(1,3));Ya(J.T(5,0),ab);Ya(J.T(6,0),bb);ub("/dev/tty",J.T(5,0));ub("/dev/tty1",J.T(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Qa(a).byteLength);return a[--b]};J.K("/dev","random",c);J.K("/dev","urandom",c);J.mkdir("/dev/shm");J.mkdir("/dev/shm/tmp")}
function wb(){J.mkdir("/proc");var a=J.mkdir("/proc/self");J.mkdir("/proc/self/fd");J.C({C(){var b=J.createNode(a,"fd",16895,73);b.v={lookup(c,d){var f=W(+d);c={parent:null,C:{Ja:"fake"},v:{readlink:()=>f.path}};return c.parent=c}};return b}},{},"/proc/self/fd")}function xb(a,b,c,d){a="string"==typeof a?a:V(a);b=H(a+"/"+b);return J.create(b,jb(c,d))}
function yb(a){if(!(a.ab||a.bb||a.link||a.B)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.B=ma(a.url),a.D=a.B.length}catch(b){throw new J.s(29);}}}
var J={root:null,Z:[],Fa:{},streams:[],cb:1,N:null,Ea:"/",oa:!1,ma:!0,s:class{constructor(a){this.name="ErrnoError";this.L=a}},ka:{},Va:null,da:0,Oa:class{constructor(){this.W={};this.node=null}get object(){return this.node}set object(a){this.node=a}get flags(){return this.W.flags}set flags(a){this.W.flags=a}get position(){return this.W.position}set position(a){this.W.position=a}},Na:class{constructor(a,b,c,d){a||=this;this.parent=a;this.C=a.C;this.J=null;this.id=J.cb++;this.name=b;this.mode=c;this.v=
{};this.A={};this.rdev=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get bb(){return N(this.mode)}get ab(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new J.Na(a,b,c,d);nb(a);return a},Ia(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},Pa:4096,Xa:a=>J.streams[a],kb(a,b=-1){a=
sb(a,b);a.A?.Ta?.(a);return a},Ra:{open(a){a.A=J.Wa(a.node.rdev).A;a.A.open?.(a)},H(){throw new J.s(70);}},ra:a=>a>>8,ob:a=>a&255,T:(a,b)=>a<<8|b,Wa:a=>J.Fa[a],La(a,b){function c(h){J.da--;return b(h)}function d(h){if(h){if(!d.Ua)return d.Ua=!0,c(h)}else++g>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);J.da++;1<J.da&&u(`warning: ${J.da} FS.syncfs operations in flight at once, probably just doing extra work`);var f=tb(J.root.C),g=0;f.forEach(h=>{if(!h.type.La)return d(null);h.type.La(h,a,d)})},
C(a,b,c){var d="/"===c;if(d&&J.root)throw new J.s(10);if(!d&&c){var f=U(c,{ja:!1});c=f.path;f=f.node;if(f.J)throw new J.s(10);if(!N(f.mode))throw new J.s(54);}b={type:a,aa:b,Ja:c,Z:[]};a=a.C(b);a.C=b;b.root=a;d?J.root=a:f&&(f.J=b,f.C&&f.C.Z.push(b));return a},sb(a){a=U(a,{ja:!1});if(!a.node.J)throw new J.s(28);a=a.node;var b=a.J,c=tb(b);Object.keys(J.N).forEach(d=>{for(d=J.N[d];d;){var f=d.V;c.includes(d.C)&&ob(d);d=f}});a.J=null;a.C.Z.splice(a.C.Z.indexOf(b),1)},lookup(a,b){return a.v.lookup(a,b)},
I(a,b,c){var d=U(a,{parent:!0}).node;a=I(a);if(!a||"."===a||".."===a)throw new J.s(28);var f=qb(d,a);if(f)throw new J.s(f);if(!d.v.I)throw new J.s(63);return d.v.I(d,a,b,c)},create(a,b){return J.I(a,(void 0!==b?b:438)&4095|32768,0)},mkdir(a,b){return J.I(a,(void 0!==b?b:511)&1023|16384,0)},pb(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{J.mkdir(c,b)}catch(f){if(20!=f.L)throw f;}}},symlink(a,b){if(!K(a))throw new J.s(44);var c=U(b,{parent:!0}).node;if(!c)throw new J.s(44);
b=I(b);var d=qb(c,b);if(d)throw new J.s(d);if(!c.v.symlink)throw new J.s(63);return c.v.symlink(c,b,a)},rename(a,b){var c=Ma(a),d=Ma(b),f=I(a),g=I(b);var h=U(a,{parent:!0});var l=h.node;h=U(b,{parent:!0});h=h.node;if(!l||!h)throw new J.s(44);if(l.C!==h.C)throw new J.s(75);var p=O(l,f);a=Ra(a,d);if("."!==a.charAt(0))throw new J.s(28);a=Ra(b,c);if("."!==a.charAt(0))throw new J.s(55);try{var n=O(h,g)}catch(r){}if(p!==n){b=N(p.mode);if(f=rb(l,f,b))throw new J.s(f);if(f=n?rb(h,g,b):qb(h,g))throw new J.s(f);
if(!l.v.rename)throw new J.s(63);if(p.J||n&&n.J)throw new J.s(10);if(h!==l&&(f=T(l,"w")))throw new J.s(f);ob(p);try{l.v.rename(p,h,g),p.parent=h}catch(r){throw r;}finally{nb(p)}}},rmdir(a){var b=U(a,{parent:!0}).node;a=I(a);var c=O(b,a),d=rb(b,a,!0);if(d)throw new J.s(d);if(!b.v.rmdir)throw new J.s(63);if(c.J)throw new J.s(10);b.v.rmdir(b,a);ob(c)},readdir(a){a=U(a,{M:!0}).node;if(!a.v.readdir)throw new J.s(54);return a.v.readdir(a)},unlink(a){var b=U(a,{parent:!0}).node;if(!b)throw new J.s(44);a=
I(a);var c=O(b,a),d=rb(b,a,!1);if(d)throw new J.s(d);if(!b.v.unlink)throw new J.s(63);if(c.J)throw new J.s(10);b.v.unlink(b,a);ob(c)},readlink(a){a=U(a).node;if(!a)throw new J.s(44);if(!a.v.readlink)throw new J.s(28);return K(V(a.parent),a.v.readlink(a))},stat(a,b){a=U(a,{M:!b}).node;if(!a)throw new J.s(44);if(!a.v.G)throw new J.s(63);return a.v.G(a)},lstat(a){return J.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?U(a,{M:!c}).node:a;if(!a.v.F)throw new J.s(63);a.v.F(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},
lchmod(a,b){J.chmod(a,b,!0)},fchmod(a,b){a=W(a);J.chmod(a.node,b)},chown(a,b,c,d){a="string"==typeof a?U(a,{M:!d}).node:a;if(!a.v.F)throw new J.s(63);a.v.F(a,{timestamp:Date.now()})},lchown(a,b,c){J.chown(a,b,c,!0)},fchown(a,b,c){a=W(a);J.chown(a.node,b,c)},truncate(a,b){if(0>b)throw new J.s(28);a="string"==typeof a?U(a,{M:!0}).node:a;if(!a.v.F)throw new J.s(63);if(N(a.mode))throw new J.s(31);if(!J.isFile(a.mode))throw new J.s(28);var c=T(a,"w");if(c)throw new J.s(c);a.v.F(a,{size:b,timestamp:Date.now()})},
mb(a,b){a=W(a);if(0===(a.flags&2097155))throw new J.s(28);J.truncate(a.node,b)},tb(a,b,c){a=U(a,{M:!0}).node;a.v.F(a,{timestamp:Math.max(b,c)})},open(a,b,c){if(""===a)throw new J.s(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var f=a;else{a=H(a);try{f=U(a,{M:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(f){if(b&128)throw new J.s(20);
}else f=J.I(a,c,0),d=!0;if(!f)throw new J.s(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!N(f.mode))throw new J.s(54);if(!d&&(c=f?40960===(f.mode&61440)?32:N(f.mode)&&("r"!==pb(b)||b&512)?31:T(f,pb(b)):44))throw new J.s(c);b&512&&!d&&J.truncate(f,0);b&=-131713;f=sb({node:f,path:V(f),flags:b,seekable:!0,position:0,A:f.A,eb:[],error:!1});f.A.open&&f.A.open(f);!e.logReadFiles||b&1||(J.ua||(J.ua={}),a in J.ua||(J.ua[a]=1));return f},close(a){if(null===a.fd)throw new J.s(8);a.la&&(a.la=null);try{a.A.close&&
a.A.close(a)}catch(b){throw b;}finally{J.streams[a.fd]=null}a.fd=null},H(a,b,c){if(null===a.fd)throw new J.s(8);if(!a.seekable||!a.A.H)throw new J.s(70);if(0!=c&&1!=c&&2!=c)throw new J.s(28);a.position=a.A.H(a,b,c);a.eb=[];return a.position},read(a,b,c,d,f){if(0>d||0>f)throw new J.s(28);if(null===a.fd)throw new J.s(8);if(1===(a.flags&2097155))throw new J.s(8);if(N(a.node.mode))throw new J.s(31);if(!a.A.read)throw new J.s(28);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new J.s(70);
b=a.A.read(a,b,c,d,f);g||(a.position+=b);return b},write(a,b,c,d,f,g){if(0>d||0>f)throw new J.s(28);if(null===a.fd)throw new J.s(8);if(0===(a.flags&2097155))throw new J.s(8);if(N(a.node.mode))throw new J.s(31);if(!a.A.write)throw new J.s(28);a.seekable&&a.flags&1024&&J.H(a,0,2);var h="undefined"!=typeof f;if(!h)f=a.position;else if(!a.seekable)throw new J.s(70);b=a.A.write(a,b,c,d,f,g);h||(a.position+=b);return b},Y(a,b,c){if(null===a.fd)throw new J.s(8);if(0>b||0>=c)throw new J.s(28);if(0===(a.flags&
2097155))throw new J.s(8);if(!J.isFile(a.node.mode)&&!N(a.node.mode))throw new J.s(43);if(!a.A.Y)throw new J.s(138);a.A.Y(a,b,c)},S(a,b,c,d,f){if(0!==(d&2)&&0===(f&2)&&2!==(a.flags&2097155))throw new J.s(2);if(1===(a.flags&2097155))throw new J.s(2);if(!a.A.S)throw new J.s(43);if(!b)throw new J.s(28);return a.A.S(a,b,c,d,f)},U(a,b,c,d,f){return a.A.U?a.A.U(a,b,c,d,f):0},pa(a,b,c){if(!a.A.pa)throw new J.s(59);return a.A.pa(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";
if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=J.open(a,b.flags);a=J.stat(a).size;var f=new Uint8Array(a);J.read(d,f,0,a,0);"utf8"===b.encoding?c=L(f,0):"binary"===b.encoding&&(c=f);J.close(d);return c},writeFile(a,b,c={}){c.flags=c.flags||577;a=J.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(Ua(b)+1);b=Va(b,d,0,d.length);J.write(a,d,0,b,void 0,c.Qa)}else if(ArrayBuffer.isView(b))J.write(a,b,0,b.byteLength,void 0,c.Qa);
else throw Error("Unsupported data type");J.close(a)},cwd:()=>J.Ea,chdir(a){a=U(a,{M:!0});if(null===a.node)throw new J.s(44);if(!N(a.node.mode))throw new J.s(54);var b=T(a.node,"x");if(b)throw new J.s(b);J.Ea=a.path},xa(){[44].forEach(a=>{J.ka[a]=new J.s(a);J.ka[a].stack="<generic error, no stack>"});J.N=Array(4096);J.C(M,{},"/");J.mkdir("/tmp");J.mkdir("/home");J.mkdir("/home/web_user");vb();wb();J.Va={MEMFS:M,NODEFS:Q,WORKERFS:S}},na(a,b,c){J.oa=!0;a?J.K("/dev","stdin",a):J.symlink("/dev/tty","/dev/stdin");
b?J.K("/dev","stdout",null,b):J.symlink("/dev/tty","/dev/stdout");c?J.K("/dev","stderr",null,c):J.symlink("/dev/tty1","/dev/stderr");J.open("/dev/stdin",0);J.open("/dev/stdout",1);J.open("/dev/stderr",1)},qb(){J.oa=!1;for(var a=0;a<J.streams.length;a++){var b=J.streams[a];b&&J.close(b)}},lb(a,b){try{var c=U(a,{M:!b});a=c.path}catch(g){}var d=!1,f=null;try{c=U(a,{parent:!0}),I(a),c=U(a,{M:!b}),d=!0,f=c.node}catch(g){}return d?f:null},Da(a,b){a="string"==typeof a?a:V(a);for(b=b.split("/").reverse();b.length;){var c=
b.pop();if(c){var d=H(a+"/"+c);try{J.mkdir(d)}catch(f){}a=d}}return d},ha(a,b,c,d,f,g){var h=b;a&&(a="string"==typeof a?a:V(a),h=b?H(a+"/"+b):a);a=jb(d,f);h=J.create(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(f=c.length;d<f;++d)b[d]=c.charCodeAt(d);c=b}J.chmod(h,a|146);b=J.open(h,577);J.write(b,c,0,c.length,0,g);J.close(b);J.chmod(h,a)}},K(a,b,c,d){a=Oa("string"==typeof a?a:V(a),b);b=jb(!!c,!!d);J.K.ra||(J.K.ra=64);var f=J.T(J.K.ra++,0);Za(f,{open(g){g.seekable=!1},close(){d?.buffer?.length&&
d(10)},read(g,h,l,p){for(var n=0,r=0;r<p;r++){try{var m=c()}catch(t){throw new J.s(29);}if(void 0===m&&0===n)throw new J.s(6);if(null===m||void 0===m)break;n++;h[l+r]=m}n&&(g.node.timestamp=Date.now());return n},write(g,h,l,p){for(var n=0;n<p;n++)try{d(h[l+n])}catch(r){throw new J.s(29);}p&&(g.node.timestamp=Date.now());return n}});return ub(a,b,f)},ia(a,b,c,d,f){function g(m,t,x,y,z){m=m.node.B;if(z>=m.length)return 0;y=Math.min(m.length-z,y);if(m.slice)for(var C=0;C<y;C++)t[x+C]=m[z+C];else for(C=
0;C<y;C++)t[x+C]=m.get(z+C);return y}class h{constructor(){this.ea=!1;this.ba=[];this.ya=void 0;this.za=this.Aa=0}get(m){if(!(m>this.length-1||0>m)){var t=m%this.chunkSize;return this.ya(m/this.chunkSize|0)[t]}}Ma(m){this.ya=m}Ba(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);var t=Number(m.getResponseHeader("Content-length")),x,y=(x=m.getResponseHeader("Accept-Ranges"))&&"bytes"===
x;m=(x=m.getResponseHeader("Content-Encoding"))&&"gzip"===x;var z=1048576;y||(z=t);var C=this;C.Ma(Y=>{var ha=Y*z,Z=(Y+1)*z-1;Z=Math.min(Z,t-1);if("undefined"==typeof C.ba[Y]){var Mb=C.ba;if(ha>Z)throw Error("invalid range ("+ha+", "+Z+") or no bytes requested!");if(Z>t-1)throw Error("only "+t+" bytes available! programmer error!");var D=new XMLHttpRequest;D.open("GET",c,!1);t!==z&&D.setRequestHeader("Range","bytes="+ha+"-"+Z);D.responseType="arraybuffer";D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");
D.send(null);if(!(200<=D.status&&300>D.status||304===D.status))throw Error("Couldn't load "+c+". Status: "+D.status);ha=void 0!==D.response?new Uint8Array(D.response||[]):Wa(D.responseText||"");Mb[Y]=ha}if("undefined"==typeof C.ba[Y])throw Error("doXHR failed!");return C.ba[Y]});if(m||!t)z=t=1,z=t=this.ya(0).length,pa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Aa=t;this.za=z;this.ea=!0}get length(){this.ea||this.Ba();return this.Aa}get chunkSize(){this.ea||
this.Ba();return this.za}}if("undefined"!=typeof XMLHttpRequest){if(!ea)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var l=new h;var p=void 0}else p=c,l=void 0;var n=xb(a,b,d,f);l?n.B=l:p&&(n.B=null,n.url=p);Object.defineProperties(n,{D:{get:function(){return this.B.length}}});var r={};Object.keys(n.A).forEach(m=>{var t=n.A[m];r[m]=(...x)=>{yb(n);return t(...x)}});r.read=(m,t,x,y,z)=>{yb(n);return g(m,t,x,y,z)};r.S=(m,t,
x)=>{yb(n);var y=db(t);if(!y)throw new J.s(48);g(m,w,y,t,x);return{sa:y,ga:!0}};n.A=r;return n}},Ka=void 0,zb={},Ab=a=>{if(a instanceof Ia||"unwind"==a)return v;ka(1,a)},Bb=0,Cb=a=>{v=a;0<Bb||(ra=!0);ka(a,new Ia(a))},Db=a=>{v=a;Cb(a)},Eb=a=>{if(!ra)try{if(a(),!(0<Bb))try{v=a=v,Cb(a)}catch(b){Ab(b)}}catch(b){Ab(b)}},Fb;Fb=()=>performance.now();var Gb=J.Da,Hb=J.ia,Ib=J.K;J.Sa=ib;J.xa();e.FS_createPath=J.Da;e.FS_createDataFile=J.ha;e.FS_createPreloadedFile=J.Sa;e.FS_unlink=J.unlink;
e.FS_createLazyFile=J.ia;e.FS_createDevice=J.K;k&&Q.xa();
var Kb={o:function(a,b,c){Ka=c;try{var d=W(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.P.Ya){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var f=G();B[f>>2]=25856;B[f+4>>2]=5;B[f+8>>2]=191;B[f+12>>2]=35387;for(var g=0;32>g;g++)w[f+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.P.Za)for(f=G(),a=[],g=0;32>g;g++)a.push(w[f+g+17]);return 0;case 21519:if(!d.tty)return-59;
f=G();return B[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=G(),J.pa(d,b,f);case 21523:if(!d.tty)return-59;d.tty.P.$a&&(g=[24,80],f=G(),sa[f>>1]=g[0],sa[f+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof J||"ErrnoError"!==h.name)throw h;return-h.L}},c:function(a,b,c,d){Ka=d;try{b=b?L(A,b):"";var f=b;if("/"===f.charAt(0))b=f;else{var g=-100===a?J.cwd():W(a).path;if(0==f.length)throw new J.s(44);b=H(g+
"/"+f)}var h=d?G():0;return J.open(b,c,h).fd}catch(l){if("undefined"==typeof J||"ErrnoError"!==l.name)throw l;return-l.L}},m:()=>{Ca("")},d:(a,b)=>{Va(ja||"./this.program",A,a,b)},k:()=>{Bb=0},e:function(a,b,c,d,f,g,h){f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{if(isNaN(f))return 61;var l=W(d),p=J.S(l,a,f,b,c),n=p.sa;B[g>>2]=p.ga;E[h>>2]=n;return 0}catch(r){if("undefined"==typeof J||"ErrnoError"!==r.name)throw r;return-r.L}},f:function(a,b,c,d,f,g){g=-9007199254740992>g||9007199254740992<
g?NaN:Number(g);try{var h=W(f);if(c&2){c=g;if(!J.isFile(h.node.mode))throw new J.s(43);if(!(d&2)){var l=A.slice(a,a+b);J.U(h,l,c,b,d)}}}catch(p){if("undefined"==typeof J||"ErrnoError"!==p.name)throw p;return-p.L}},l:(a,b)=>{zb[a]&&(clearTimeout(zb[a].id),delete zb[a]);if(!b)return 0;var c=setTimeout(()=>{delete zb[a];Eb(()=>Jb(a,Fb()))},b);zb[a]={id:c,rb:b};return 0},n:a=>{var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,
65536*Math.ceil(Math.max(a,d)/65536))-qa.buffer.byteLength+65535)/65536;try{qa.grow(d);ua();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},b:Db,a:function(a){try{var b=W(a);J.close(b);return 0}catch(c){if("undefined"==typeof J||"ErrnoError"!==c.name)throw c;return c.L}},i:function(a,b,c,d){try{a:{var f=W(a);a=b;for(var g,h=b=0;h<c;h++){var l=E[a>>2],p=E[a+4>>2];a+=8;var n=J.read(f,w,l,p,g);if(0>n){var r=-1;break a}b+=n;if(n<p)break;"undefined"!=typeof g&&(g+=n)}r=b}E[d>>2]=r;return 0}catch(m){if("undefined"==
typeof J||"ErrnoError"!==m.name)throw m;return m.L}},g:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var f=W(a);J.H(f,b,c);ta[d>>3]=BigInt(f.position);f.la&&0===b&&0===c&&(f.la=null);return 0}catch(g){if("undefined"==typeof J||"ErrnoError"!==g.name)throw g;return g.L}},h:function(a,b,c,d){try{a:{var f=W(a);a=b;for(var g,h=b=0;h<c;h++){var l=E[a>>2],p=E[a+4>>2];a+=8;var n=J.write(f,w,l,p,g);if(0>n){var r=-1;break a}b+=n;if(n<p)break;"undefined"!=
typeof g&&(g+=n)}r=b}E[d>>2]=r;return 0}catch(m){if("undefined"==typeof J||"ErrnoError"!==m.name)throw m;return m.L}},j:Cb},X=function(){var a={a:Kb};F++;Ea||=e.locateFile?Da("bsdiff.wasm")?"bsdiff.wasm":e.locateFile?e.locateFile("bsdiff.wasm",q):q+"bsdiff.wasm":(new URL("bsdiff.wasm",import.meta.url)).href;Ha(a,function(b){X=b.instance.exports;qa=X.p;ua();wa.unshift(X.q);Ba("wasm-instantiate")}).catch(ba);return{}}(),Lb=e._main=(a,b)=>(Lb=e._main=X.r)(a,b),cb=(a,b)=>(cb=X.t)(a,b),Jb=(a,
b)=>(Jb=X.u)(a,b),Nb=a=>(Nb=X.x)(a);e.addRunDependency=function(){F++};e.removeRunDependency=Ba;e.callMain=Ob;e.ENV={};e.FS_createPreloadedFile=ib;e.FS_unlink=a=>J.unlink(a);e.FS_createPath=Gb;e.FS_createDevice=Ib;e.FS=J;e.FS_createDataFile=(a,b,c,d,f,g)=>{J.ha(a,b,c,d,f,g)};e.FS_createLazyFile=Hb;e.NODEFS=Q;e.WORKERFS=S;var Pb;Aa=function Qb(){Pb||Rb();Pb||(Aa=Qb)};
function Ob(a=[]){var b=Lb;a.unshift(ja);var c=a.length,d=Nb(4*(c+1)),f=d;a.forEach(h=>{var l=E,p=f>>2,n=Ua(h)+1,r=Nb(n);Va(h,A,r,n);l[p]=r;f+=4});E[f>>2]=0;try{var g=b(c,d);Db(g,!0);return g}catch(h){return Ab(h)}}function Rb(){var a=ia;if(!(0<F)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;){var b=e.preRun.shift();va.unshift(b)}Ja(va);0<F||Pb||(Pb=!0,e.calledRun=!0,ra||(e.noFSInit||J.oa||J.na(),J.ma=!1,Ja(wa),Ja(xa),aa(e),Sb&&Ob(a),Ja(ya)))}}var Sb=!1;
e.noInitialRun&&(Sb=!1);Rb();Object.assign(J,{init:J.na,mkdir:J.mkdir,mount:J.C,chdir:J.chdir,writeFile:J.writeFile,readFile:J.readFile,createLazyFile:J.ia,setIgnorePermissions:function(a){J.ma=a}});moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default loadBsdiff;
