
var loadBspatch = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var e=moduleArg,aa,ba,ca=new Promise((a,b)=>{aa=a;ba=b}),da="object"==typeof window,l="function"==typeof importScripts,p="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node;if(p){const {createRequire:a}=await import("module");var require=a(import.meta.url)}var ea=Object.assign({},e),ha=[],ia="./this.program",ja=(a,b)=>{throw b;},t="",ka,la;
if(p){var fs=require("fs"),ma=require("path");t=require("url").fileURLToPath(new URL("./",import.meta.url));la=a=>{a=na(a)?new URL(a):ma.normalize(a);return fs.readFileSync(a)};ka=a=>{a=na(a)?new URL(a):ma.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,f)=>{d?c(d):b(f.buffer)})})};!e.thisProgram&&1<process.argv.length&&(ia=process.argv[1].replace(/\\/g,"/"));ha=process.argv.slice(2);ja=(a,b)=>{process.exitCode=a;throw b;}}else if(da||l)l?t=self.location.href:"undefined"!=
typeof document&&document.currentScript&&(t=document.currentScript.src),_scriptName&&(t=_scriptName),t.startsWith("blob:")?t="":t=t.substr(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1),l&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=a=>na(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c(d.status)};
d.onerror=c;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var oa=e.print||console.log.bind(console),u=e.printErr||console.error.bind(console);Object.assign(e,ea);ea=null;var pa,qa=!1,v,x,ra,sa,z,C,ta;
function ua(){var a=pa.buffer;e.HEAP8=x=new Int8Array(a);e.HEAP16=sa=new Int16Array(a);e.HEAPU8=ra=new Uint8Array(a);e.HEAPU16=new Uint16Array(a);e.HEAP32=z=new Int32Array(a);e.HEAPU32=C=new Uint32Array(a);e.HEAPF32=new Float32Array(a);e.HEAPF64=new Float64Array(a);e.HEAP64=ta=new BigInt64Array(a);e.HEAPU64=new BigUint64Array(a)}var va=[],wa=[],xa=[],ya=[],D=0,za=null,Aa=null;function Ba(){D--;if(0==D&&(null!==za&&(clearInterval(za),za=null),Aa)){var a=Aa;Aa=null;a()}}
function E(a){a="Aborted("+a+")";u(a);qa=!0;v=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}var Ca=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),Da;function Ea(a){return ka(a).then(b=>new Uint8Array(b),()=>{if(la)var b=la(a);else throw"both async and sync fetching of the wasm failed";return b})}
function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{u(`failed to asynchronously prepare wasm: ${d}`);E(d)})}function Ga(a,b){var c=Da;return"function"!=typeof WebAssembly.instantiateStreaming||Ca(c)||na(c)||p||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(f){u(`wasm streaming compile failed: ${f}`);u("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}
function Ha(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Ia=a=>{for(;0<a.length;)a.shift()(e)};function G(){var a=z[+Ja>>2];Ja+=4;return a}
var Ka=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},H=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ka(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},La=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},I=a=>{if("/"===
a)return"/";a=H(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ma=(...a)=>H(a.join("/")),Na=(a,b)=>H(a+"/"+b),Oa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>crypto.getRandomValues(c);if(p)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}E("initRandomDevice")},Pa=a=>(Pa=Oa())(a),K=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=
0<=d?a[d]:J.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ka(b.split("/").filter(f=>!!f),!c).join("/");return(c?"/":"")+b||"."},Qa=(a,b)=>{function c(h){for(var m=0;m<h.length&&""===h[m];m++);for(var n=h.length-1;0<=n&&""===h[n];n--);return m>n?[]:h.slice(m,n-m+1)}a=K(a).substr(1);b=K(b).substr(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),f=d,g=0;g<d;g++)if(a[g]!==b[g]){f=
g;break}d=[];for(g=f;g<a.length;g++)d.push("..");d=d.concat(b.slice(f));return d.join("/")},Ra="undefined"!=typeof TextDecoder?new TextDecoder:void 0,L=(a,b)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Ra)return Ra.decode(a.subarray(b,d));for(c="";b<d;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))c+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?c+=String.fromCharCode(f):(f-=65536,c+=String.fromCharCode(55296|
f>>10,56320|f&1023))}}else c+=String.fromCharCode(f)}return c},Sa=[],Ta=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ua=(a,b,c,d)=>{if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var m=a.charCodeAt(++g);h=65536+((h&1023)<<10)|m&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|
h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f};function Va(a){var b=Array(Ta(a)+1);a=Ua(a,b,0,b.length);b.length=a;return b}var Wa=[];function Xa(a,b){Wa[a]={input:[],output:[],O:b};Ya(a,Za)}
var Za={open(a){var b=Wa[a.node.rdev];if(!b)throw new J.s(43);a.tty=b;a.seekable=!1},close(a){a.tty.O.fsync(a.tty)},fsync(a){a.tty.O.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.O.Fa)throw new J.s(60);for(var f=0,g=0;g<d;g++){try{var h=a.tty.O.Fa(a.tty)}catch(m){throw new J.s(29);}if(void 0===h&&0===f)throw new J.s(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write(a,b,c,d){if(!a.tty||!a.tty.O.ra)throw new J.s(60);try{for(var f=0;f<d;f++)a.tty.O.ra(a.tty,
b[c+f])}catch(g){throw new J.s(29);}d&&(a.node.timestamp=Date.now());return f}},$a={Fa(){a:{if(!Sa.length){var a=null;if(p){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(f){if(f.toString().includes("EOF"))c=0;else throw f;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Sa=Va(a)}a=Sa.shift()}return a},ra(a,b){null===b||10===b?(oa(L(a.output,
0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(oa(L(a.output,0)),a.output=[])},Xa(){return{hb:25856,jb:5,gb:191,ib:35387,fb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ya(){return 0},Za(){return[24,80]}},ab={ra(a,b){null===b||10===b?(u(L(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(u(L(a.output,0)),a.output=[])}};
function bb(a,b){var c=a.B?a.B.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.B,a.B=new Uint8Array(b),0<a.D&&a.B.set(c.subarray(0,a.D),0))}
var M={N:null,C(){return M.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||J.isFIFO(c))throw new J.s(63);M.N||(M.N={dir:{node:{G:M.v.G,F:M.v.F,lookup:M.v.lookup,I:M.v.I,rename:M.v.rename,unlink:M.v.unlink,rmdir:M.v.rmdir,readdir:M.v.readdir,symlink:M.v.symlink},stream:{H:M.A.H}},file:{node:{G:M.v.G,F:M.v.F},stream:{H:M.A.H,read:M.A.read,write:M.A.write,Y:M.A.Y,T:M.A.T,W:M.A.W}},link:{node:{G:M.v.G,F:M.v.F,readlink:M.v.readlink},stream:{}},Aa:{node:{G:M.v.G,F:M.v.F},stream:J.Qa}});
c=J.createNode(a,b,c,d);N(c.mode)?(c.v=M.N.dir.node,c.A=M.N.dir.stream,c.B={}):J.isFile(c.mode)?(c.v=M.N.file.node,c.A=M.N.file.stream,c.D=0,c.B=null):40960===(c.mode&61440)?(c.v=M.N.link.node,c.A=M.N.link.stream):8192===(c.mode&61440)&&(c.v=M.N.Aa.node,c.A=M.N.Aa.stream);c.timestamp=Date.now();a&&(a.B[b]=c,a.timestamp=c.timestamp);return c},nb(a){return a.B?a.B.subarray?a.B.subarray(0,a.D):new Uint8Array(a.B):new Uint8Array(0)},v:{G(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=
a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;N(a.mode)?b.size=4096:J.isFile(a.mode)?b.size=a.D:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.P=4096;b.blocks=Math.ceil(b.size/b.P);return b},F(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.D!=b))if(0==b)a.B=null,a.D=0;else{var c=a.B;a.B=new Uint8Array(b);c&&a.B.set(c.subarray(0,Math.min(b,
a.D)));a.D=b}},lookup(){throw J.ja[44];},I(a,b,c,d){return M.createNode(a,b,c,d)},rename(a,b,c){if(N(a.mode)){try{var d=O(b,c)}catch(g){}if(d)for(var f in d.B)throw new J.s(55);}delete a.parent.B[a.name];a.parent.timestamp=Date.now();a.name=c;b.B[c]=a;b.timestamp=a.parent.timestamp},unlink(a,b){delete a.B[b];a.timestamp=Date.now()},rmdir(a,b){var c=O(a,b),d;for(d in c.B)throw new J.s(55);delete a.B[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.B))b.push(c);return b},
symlink(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new J.s(28);return a.link}},A:{read(a,b,c,d,f){var g=a.node.B;if(f>=a.node.D)return 0;a=Math.min(a.node.D-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write(a,b,c,d,f,g){b.buffer===x.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.B||a.B.subarray)){if(g)return a.B=b.subarray(c,c+d),a.D=d;if(0===a.D&&0===f)return a.B=
b.slice(c,c+d),a.D=d;if(f+d<=a.D)return a.B.set(b.subarray(c,c+d),f),d}bb(a,f+d);if(a.B.subarray&&b.subarray)a.B.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.B[f+g]=b[c+g];a.D=Math.max(a.D,f+d);return d},H(a,b,c){1===c?b+=a.position:2===c&&J.isFile(a.node.mode)&&(b+=a.node.D);if(0>b)throw new J.s(28);return b},Y(a,b,c){bb(a.node,b+c);a.node.D=Math.max(a.node.D,b+c)},T(a,b,c,d,f){if(!J.isFile(a.node.mode))throw new J.s(43);a=a.node.B;if(f&2||!a||a.buffer!==x.buffer){d=!0;E();f=void 0;if(!f)throw new J.s(48);
if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);x.set(a,f)}}else d=!1,f=a.byteOffset;return{cb:f,Oa:d}},W(a,b,c,d){M.A.write(a,b,0,d,c,!1);return 0}}},cb=(a,b,c)=>{var d=`al ${a}`;ka(a).then(f=>{b(new Uint8Array(f));d&&Ba(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&D++},db=[],eb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.ma();var f=!1;db.forEach(g=>{!f&&g.canHandle(b)&&(g.handle(a,b,c,d),f=!0)});return f},fb=(a,b,c,d,f,
g,h,m,n,q)=>{function k(F){function y(w){q?.();m||J.ga(a,b,w,d,f,n);g?.();Ba(A)}eb(F,r,y,()=>{h?.();Ba(A)})||y(F)}var r=b?K(H(a+"/"+b)):a,A=`cp ${r}`;D++;"string"==typeof c?cb(c,k,h):k(c)},gb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},hb={EPERM:63,ENOENT:44,ESRCH:71,EINTR:27,EIO:29,ENXIO:60,E2BIG:1,ENOEXEC:45,EBADF:8,ECHILD:12,EAGAIN:6,EWOULDBLOCK:6,ENOMEM:48,EACCES:2,EFAULT:21,ENOTBLK:105,EBUSY:10,EEXIST:20,EXDEV:75,ENODEV:43,ENOTDIR:54,EISDIR:31,EINVAL:28,ENFILE:41,EMFILE:33,ENOTTY:59,ETXTBSY:74,
EFBIG:22,ENOSPC:51,ESPIPE:70,EROFS:69,EMLINK:34,EPIPE:64,EDOM:18,ERANGE:68,ENOMSG:49,EIDRM:24,ECHRNG:106,EL2NSYNC:156,EL3HLT:107,EL3RST:108,ELNRNG:109,EUNATCH:110,ENOCSI:111,EL2HLT:112,EDEADLK:16,ENOLCK:46,EBADE:113,EBADR:114,EXFULL:115,ENOANO:104,EBADRQC:103,EBADSLT:102,EDEADLOCK:16,EBFONT:101,ENOSTR:100,ENODATA:116,ETIME:117,ENOSR:118,ENONET:119,ENOPKG:120,EREMOTE:121,ENOLINK:47,EADV:122,ESRMNT:123,ECOMM:124,EPROTO:65,EMULTIHOP:36,EDOTDOT:125,EBADMSG:9,ENOTUNIQ:126,EBADFD:127,EREMCHG:128,ELIBACC:129,
ELIBBAD:130,ELIBSCN:131,ELIBMAX:132,ELIBEXEC:133,ENOSYS:52,ENOTEMPTY:55,ENAMETOOLONG:37,ELOOP:32,EOPNOTSUPP:138,EPFNOSUPPORT:139,ECONNRESET:15,ENOBUFS:42,EAFNOSUPPORT:5,EPROTOTYPE:67,ENOTSOCK:57,ENOPROTOOPT:50,ESHUTDOWN:140,ECONNREFUSED:14,EADDRINUSE:3,ECONNABORTED:13,ENETUNREACH:40,ENETDOWN:38,ETIMEDOUT:73,EHOSTDOWN:142,EHOSTUNREACH:23,EINPROGRESS:26,EALREADY:7,EDESTADDRREQ:17,EMSGSIZE:35,EPROTONOSUPPORT:66,ESOCKTNOSUPPORT:137,EADDRNOTAVAIL:4,ENETRESET:39,EISCONN:30,ENOTCONN:53,ETOOMANYREFS:141,
EUSERS:136,EDQUOT:19,ESTALE:72,ENOTSUP:138,ENOMEDIUM:148,EILSEQ:25,EOVERFLOW:61,ECANCELED:11,ENOTRECOVERABLE:56,EOWNERDEAD:62,ESTRPIPE:135};function P(a){try{return a()}catch(b){if(!b.code)throw b;if("UNKNOWN"===b.code)throw new J.s(28);throw new J.s(hb[b.code]);}}function ib(a){var b;return P(()=>{b=fs.lstatSync(a);Q.pa&&(b.mode|=(b.mode&292)>>2);return b.mode})}function R(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.C.aa.root);b.reverse();return Ma(...b)}
var Q={pa:!1,va(){Q.pa=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);Q.Ea={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,256:a.O_NOCTTY,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY,131072:a.O_NOFOLLOW}},C(a){return Q.createNode(null,"/",ib(a.aa.root),0)},createNode(a,b,c){if(!N(c)&&!J.isFile(c)&&40960!==(c&61440))throw new J.s(28);a=J.createNode(a,b,c);a.v=Q.v;a.A=Q.A;return a},v:{G(a){var b=R(a),c;P(()=>c=fs.lstatSync(b));Q.pa&&(c.P||(c.P=4096),
c.blocks||(c.blocks=(c.size+c.P-1)/c.P|0),c.mode|=(c.mode&292)>>2);return{dev:c.dev,ino:c.ino,mode:c.mode,nlink:c.nlink,uid:c.uid,gid:c.gid,rdev:c.rdev,size:c.size,atime:c.atime,mtime:c.mtime,ctime:c.ctime,P:c.P,blocks:c.blocks}},F(a,b){var c=R(a);P(()=>{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode);void 0!==b.size&&fs.truncateSync(c,b.size)})},lookup(a,b){var c=R(a);c=H(c+"/"+b);c=ib(c);return Q.createNode(a,b,c)},I(a,b,c,d){var f=Q.createNode(a,b,c,d),g=R(f);P(()=>{N(f.mode)?fs.mkdirSync(g,
f.mode):fs.writeFileSync(g,"",{mode:f.mode})});return f},rename(a,b,c){var d=R(a),f=Na(R(b),c);P(()=>fs.renameSync(d,f));a.name=c},unlink(a,b){var c=Na(R(a),b);P(()=>fs.unlinkSync(c))},rmdir(a,b){var c=Na(R(a),b);P(()=>fs.rmdirSync(c))},readdir(a){var b=R(a);return P(()=>fs.readdirSync(b))},symlink(a,b,c){var d=Na(R(a),b);P(()=>fs.symlinkSync(c,d))},readlink(a){var b=R(a);return P(()=>fs.readlinkSync(b))}},A:{open(a){var b=R(a.node);P(()=>{if(J.isFile(a.node.mode)){a.V.Ia=1;var c=fs,d=c.openSync,
f=a.flags;f&=-2721793;var g=0,h;for(h in Q.Ea)f&h&&(g|=Q.Ea[h],f^=h);if(f)throw new J.s(28);a.$=d.call(c,b,g)}})},close(a){P(()=>{J.isFile(a.node.mode)&&a.$&&0===--a.V.Ia&&fs.closeSync(a.$)})},Sa(a){a.V.Ia++},read(a,b,c,d,f){return 0===d?0:P(()=>fs.readSync(a.$,new Int8Array(b.buffer,c,d),0,d,f))},write(a,b,c,d,f){return P(()=>fs.writeSync(a.$,new Int8Array(b.buffer,c,d),0,d,f))},H(a,b,c){var d=b;1===c?d+=a.position:2===c&&J.isFile(a.node.mode)&&P(()=>{d+=fs.fstatSync(a.$).size});if(0>d)throw new J.s(28);
return d},T(a,b,c){if(!J.isFile(a.node.mode))throw new J.s(43);E();Q.A.read(a,x,void 0,b,c);return{cb:void 0,Oa:!0}},W(a,b,c,d){Q.A.write(a,b,0,d,c,!1);return 0}}},S={fa:16895,X:33279,ta:null,C(a){function b(g){g=g.split("/");for(var h=d,m=0;m<g.length-1;m++){var n=g.slice(0,m+1).join("/");let q,k;(q=f)[k=n]||(q[k]=S.createNode(h,g[m],S.fa,0));h=f[n]}return h}function c(g){g=g.split("/");return g[g.length-1]}l||E();S.ta||(S.ta=new FileReaderSync);var d=S.createNode(null,"/",S.fa,0),f={};Array.prototype.forEach.call(a.aa.files||
[],function(g){S.createNode(b(g.name),c(g.name),S.X,0,g,g.lastModifiedDate)});(a.aa.blobs||[]).forEach(function(g){S.createNode(b(g.name),c(g.name),S.X,0,g.data)});(a.aa.packages||[]).forEach(function(g){g.metadata.files.forEach(function(h){var m=h.filename.substr(1);S.createNode(b(m),c(m),S.X,0,g.blob.slice(h.start,h.end))})});return d},createNode(a,b,c,d,f,g){d=J.createNode(a,b,c);d.mode=c;d.v=S.v;d.A=S.A;d.timestamp=(g||new Date).getTime();S.X!==S.fa||E();c===S.X?(d.size=f.size,d.B=f):(d.size=
4096,d.B={});a&&(a.B[b]=d);return d},v:{G(a){return{dev:1,ino:a.id,mode:a.mode,nlink:1,uid:0,gid:0,rdev:0,size:a.size,atime:new Date(a.timestamp),mtime:new Date(a.timestamp),ctime:new Date(a.timestamp),P:4096,blocks:Math.ceil(a.size/4096)}},F(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp)},lookup(){throw new J.s(44);},I(){throw new J.s(63);},rename(){throw new J.s(63);},unlink(){throw new J.s(63);},rmdir(){throw new J.s(63);},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.B))b.push(c);
return b},symlink(){throw new J.s(63);}},A:{read(a,b,c,d,f){if(f>=a.node.size)return 0;a=a.node.B.slice(f,f+d);d=S.ta.readAsArrayBuffer(a);b.set(new Uint8Array(d),c);return a.size},write(){throw new J.s(29);},H(a,b,c){1===c?b+=a.position:2===c&&J.isFile(a.node.mode)&&(b+=a.node.size);if(0>b)throw new J.s(28);return b}}};function Ya(a,b){J.Da[a]={A:b}}function N(a){return 16384===(a&61440)}
function O(a,b){var c=N(a.mode)?(c=T(a,"x"))?c:a.v.lookup?0:2:54;if(c)throw new J.s(c);for(c=J.M[jb(a.id,b)];c;c=c.U){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return J.lookup(a,b)}
function U(a,b={}){a=K(a);if(!a)return{path:"",node:null};b=Object.assign({ia:!0,ua:0},b);if(8<b.ua)throw new J.s(32);a=a.split("/").filter(h=>!!h);for(var c=J.root,d="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;c=O(c,a[f]);d=H(d+"/"+a[f]);c.J&&(!g||g&&b.ia)&&(c=c.J.root);if(!g||b.L)for(g=0;40960===(c.mode&61440);)if(c=J.readlink(d),d=K(La(d),c),c=U(d,{ua:b.ua+1}).node,40<g++)throw new J.s(32);}return{path:d,node:c}}
function V(a){for(var b;;){if(J.Ga(a))return a=a.C.Ha,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function jb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%J.M.length}function kb(a){var b=jb(a.parent.id,a.name);a.U=J.M[b];J.M[b]=a}function lb(a){var b=jb(a.parent.id,a.name);if(J.M[b]===a)J.M[b]=a.U;else for(b=J.M[b];b;){if(b.U===a){b.U=a.U;break}b=b.U}}function mb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function T(a,b){if(J.la)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function nb(a,b){try{return O(a,b),20}catch(c){}return T(a,"wx")}function ob(a,b,c){try{var d=O(a,b)}catch(f){return f.R}if(a=T(a,"wx"))return a;if(c){if(!N(d.mode))return 54;if(J.Ga(d)||V(d)===J.cwd())return 10}else if(N(d.mode))return 31;return 0}function Y(a){a=J.Wa(a);if(!a)throw new J.s(8);return a}
function pb(a,b=-1){a=Object.assign(new J.Ma,a);if(-1==b)a:{for(b=0;b<=J.Na;b++)if(!J.streams[b])break a;throw new J.s(33);}a.fd=b;return J.streams[b]=a}function qb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.Z)}return b}function rb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return J.I(a,b|8192,c)}
function sb(){J.mkdir("/dev");Ya(J.S(1,3),{read:()=>0,write:(d,f,g,h)=>h});rb("/dev/null",J.S(1,3));Xa(J.S(5,0),$a);Xa(J.S(6,0),ab);rb("/dev/tty",J.S(5,0));rb("/dev/tty1",J.S(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Pa(a).byteLength);return a[--b]};J.K("/dev","random",c);J.K("/dev","urandom",c);J.mkdir("/dev/shm");J.mkdir("/dev/shm/tmp")}
function tb(){J.mkdir("/proc");var a=J.mkdir("/proc/self");J.mkdir("/proc/self/fd");J.C({C(){var b=J.createNode(a,"fd",16895,73);b.v={lookup(c,d){var f=Y(+d);c={parent:null,C:{Ha:"fake"},v:{readlink:()=>f.path}};return c.parent=c}};return b}},{},"/proc/self/fd")}function ub(a,b,c,d){a="string"==typeof a?a:V(a);b=H(a+"/"+b);return J.create(b,gb(c,d))}
function vb(a){if(!(a.$a||a.ab||a.link||a.B)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.B=la(a.url),a.D=a.B.length}catch(b){throw new J.s(29);}}}
var J={root:null,Z:[],Da:{},streams:[],bb:1,M:null,Ca:"/",na:!1,la:!0,s:class{constructor(a){this.name="ErrnoError";this.R=a}},ja:{},Ua:null,da:0,Ma:class{constructor(){this.V={};this.node=null}get object(){return this.node}set object(a){this.node=a}get flags(){return this.V.flags}set flags(a){this.V.flags=a}get position(){return this.V.position}set position(a){this.V.position=a}},La:class{constructor(a,b,c,d){a||=this;this.parent=a;this.C=a.C;this.J=null;this.id=J.bb++;this.name=b;this.mode=c;this.v=
{};this.A={};this.rdev=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get ab(){return N(this.mode)}get $a(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new J.La(a,b,c,d);kb(a);return a},Ga(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},Na:4096,Wa:a=>J.streams[a],kb(a,b=-1){a=
pb(a,b);a.A?.Sa?.(a);return a},Qa:{open(a){a.A=J.Va(a.node.rdev).A;a.A.open?.(a)},H(){throw new J.s(70);}},qa:a=>a>>8,ob:a=>a&255,S:(a,b)=>a<<8|b,Va:a=>J.Da[a],Ja(a,b){function c(h){J.da--;return b(h)}function d(h){if(h){if(!d.Ta)return d.Ta=!0,c(h)}else++g>=f.length&&c(null)}"function"==typeof a&&(b=a,a=!1);J.da++;1<J.da&&u(`warning: ${J.da} FS.syncfs operations in flight at once, probably just doing extra work`);var f=qb(J.root.C),g=0;f.forEach(h=>{if(!h.type.Ja)return d(null);h.type.Ja(h,a,d)})},
C(a,b,c){var d="/"===c;if(d&&J.root)throw new J.s(10);if(!d&&c){var f=U(c,{ia:!1});c=f.path;f=f.node;if(f.J)throw new J.s(10);if(!N(f.mode))throw new J.s(54);}b={type:a,aa:b,Ha:c,Z:[]};a=a.C(b);a.C=b;b.root=a;d?J.root=a:f&&(f.J=b,f.C&&f.C.Z.push(b));return a},sb(a){a=U(a,{ia:!1});if(!a.node.J)throw new J.s(28);a=a.node;var b=a.J,c=qb(b);Object.keys(J.M).forEach(d=>{for(d=J.M[d];d;){var f=d.U;c.includes(d.C)&&lb(d);d=f}});a.J=null;a.C.Z.splice(a.C.Z.indexOf(b),1)},lookup(a,b){return a.v.lookup(a,b)},
I(a,b,c){var d=U(a,{parent:!0}).node;a=I(a);if(!a||"."===a||".."===a)throw new J.s(28);var f=nb(d,a);if(f)throw new J.s(f);if(!d.v.I)throw new J.s(63);return d.v.I(d,a,b,c)},create(a,b){return J.I(a,(void 0!==b?b:438)&4095|32768,0)},mkdir(a,b){return J.I(a,(void 0!==b?b:511)&1023|16384,0)},pb(a,b){a=a.split("/");for(var c="",d=0;d<a.length;++d)if(a[d]){c+="/"+a[d];try{J.mkdir(c,b)}catch(f){if(20!=f.R)throw f;}}},symlink(a,b){if(!K(a))throw new J.s(44);var c=U(b,{parent:!0}).node;if(!c)throw new J.s(44);
b=I(b);var d=nb(c,b);if(d)throw new J.s(d);if(!c.v.symlink)throw new J.s(63);return c.v.symlink(c,b,a)},rename(a,b){var c=La(a),d=La(b),f=I(a),g=I(b);var h=U(a,{parent:!0});var m=h.node;h=U(b,{parent:!0});h=h.node;if(!m||!h)throw new J.s(44);if(m.C!==h.C)throw new J.s(75);var n=O(m,f);a=Qa(a,d);if("."!==a.charAt(0))throw new J.s(28);a=Qa(b,c);if("."!==a.charAt(0))throw new J.s(55);try{var q=O(h,g)}catch(k){}if(n!==q){b=N(n.mode);if(f=ob(m,f,b))throw new J.s(f);if(f=q?ob(h,g,b):nb(h,g))throw new J.s(f);
if(!m.v.rename)throw new J.s(63);if(n.J||q&&q.J)throw new J.s(10);if(h!==m&&(f=T(m,"w")))throw new J.s(f);lb(n);try{m.v.rename(n,h,g),n.parent=h}catch(k){throw k;}finally{kb(n)}}},rmdir(a){var b=U(a,{parent:!0}).node;a=I(a);var c=O(b,a),d=ob(b,a,!0);if(d)throw new J.s(d);if(!b.v.rmdir)throw new J.s(63);if(c.J)throw new J.s(10);b.v.rmdir(b,a);lb(c)},readdir(a){a=U(a,{L:!0}).node;if(!a.v.readdir)throw new J.s(54);return a.v.readdir(a)},unlink(a){var b=U(a,{parent:!0}).node;if(!b)throw new J.s(44);a=
I(a);var c=O(b,a),d=ob(b,a,!1);if(d)throw new J.s(d);if(!b.v.unlink)throw new J.s(63);if(c.J)throw new J.s(10);b.v.unlink(b,a);lb(c)},readlink(a){a=U(a).node;if(!a)throw new J.s(44);if(!a.v.readlink)throw new J.s(28);return K(V(a.parent),a.v.readlink(a))},stat(a,b){a=U(a,{L:!b}).node;if(!a)throw new J.s(44);if(!a.v.G)throw new J.s(63);return a.v.G(a)},lstat(a){return J.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?U(a,{L:!c}).node:a;if(!a.v.F)throw new J.s(63);a.v.F(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},
lchmod(a,b){J.chmod(a,b,!0)},fchmod(a,b){a=Y(a);J.chmod(a.node,b)},chown(a,b,c,d){a="string"==typeof a?U(a,{L:!d}).node:a;if(!a.v.F)throw new J.s(63);a.v.F(a,{timestamp:Date.now()})},lchown(a,b,c){J.chown(a,b,c,!0)},fchown(a,b,c){a=Y(a);J.chown(a.node,b,c)},truncate(a,b){if(0>b)throw new J.s(28);a="string"==typeof a?U(a,{L:!0}).node:a;if(!a.v.F)throw new J.s(63);if(N(a.mode))throw new J.s(31);if(!J.isFile(a.mode))throw new J.s(28);var c=T(a,"w");if(c)throw new J.s(c);a.v.F(a,{size:b,timestamp:Date.now()})},
mb(a,b){a=Y(a);if(0===(a.flags&2097155))throw new J.s(28);J.truncate(a.node,b)},tb(a,b,c){a=U(a,{L:!0}).node;a.v.F(a,{timestamp:Math.max(b,c)})},open(a,b,c){if(""===a)throw new J.s(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var f=a;else{a=H(a);try{f=U(a,{L:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(f){if(b&128)throw new J.s(20);
}else f=J.I(a,c,0),d=!0;if(!f)throw new J.s(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!N(f.mode))throw new J.s(54);if(!d&&(c=f?40960===(f.mode&61440)?32:N(f.mode)&&("r"!==mb(b)||b&512)?31:T(f,mb(b)):44))throw new J.s(c);b&512&&!d&&J.truncate(f,0);b&=-131713;f=pb({node:f,path:V(f),flags:b,seekable:!0,position:0,A:f.A,eb:[],error:!1});f.A.open&&f.A.open(f);!e.logReadFiles||b&1||(J.sa||(J.sa={}),a in J.sa||(J.sa[a]=1));return f},close(a){if(null===a.fd)throw new J.s(8);a.ka&&(a.ka=null);try{a.A.close&&
a.A.close(a)}catch(b){throw b;}finally{J.streams[a.fd]=null}a.fd=null},H(a,b,c){if(null===a.fd)throw new J.s(8);if(!a.seekable||!a.A.H)throw new J.s(70);if(0!=c&&1!=c&&2!=c)throw new J.s(28);a.position=a.A.H(a,b,c);a.eb=[];return a.position},read(a,b,c,d,f){if(0>d||0>f)throw new J.s(28);if(null===a.fd)throw new J.s(8);if(1===(a.flags&2097155))throw new J.s(8);if(N(a.node.mode))throw new J.s(31);if(!a.A.read)throw new J.s(28);var g="undefined"!=typeof f;if(!g)f=a.position;else if(!a.seekable)throw new J.s(70);
b=a.A.read(a,b,c,d,f);g||(a.position+=b);return b},write(a,b,c,d,f,g){if(0>d||0>f)throw new J.s(28);if(null===a.fd)throw new J.s(8);if(0===(a.flags&2097155))throw new J.s(8);if(N(a.node.mode))throw new J.s(31);if(!a.A.write)throw new J.s(28);a.seekable&&a.flags&1024&&J.H(a,0,2);var h="undefined"!=typeof f;if(!h)f=a.position;else if(!a.seekable)throw new J.s(70);b=a.A.write(a,b,c,d,f,g);h||(a.position+=b);return b},Y(a,b,c){if(null===a.fd)throw new J.s(8);if(0>b||0>=c)throw new J.s(28);if(0===(a.flags&
2097155))throw new J.s(8);if(!J.isFile(a.node.mode)&&!N(a.node.mode))throw new J.s(43);if(!a.A.Y)throw new J.s(138);a.A.Y(a,b,c)},T(a,b,c,d,f){if(0!==(d&2)&&0===(f&2)&&2!==(a.flags&2097155))throw new J.s(2);if(1===(a.flags&2097155))throw new J.s(2);if(!a.A.T)throw new J.s(43);if(!b)throw new J.s(28);return a.A.T(a,b,c,d,f)},W(a,b,c,d,f){return a.A.W?a.A.W(a,b,c,d,f):0},oa(a,b,c){if(!a.A.oa)throw new J.s(59);return a.A.oa(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";
if("utf8"!==b.encoding&&"binary"!==b.encoding)throw Error(`Invalid encoding type "${b.encoding}"`);var c,d=J.open(a,b.flags);a=J.stat(a).size;var f=new Uint8Array(a);J.read(d,f,0,a,0);"utf8"===b.encoding?c=L(f,0):"binary"===b.encoding&&(c=f);J.close(d);return c},writeFile(a,b,c={}){c.flags=c.flags||577;a=J.open(a,c.flags,c.mode);if("string"==typeof b){var d=new Uint8Array(Ta(b)+1);b=Ua(b,d,0,d.length);J.write(a,d,0,b,void 0,c.Pa)}else if(ArrayBuffer.isView(b))J.write(a,b,0,b.byteLength,void 0,c.Pa);
else throw Error("Unsupported data type");J.close(a)},cwd:()=>J.Ca,chdir(a){a=U(a,{L:!0});if(null===a.node)throw new J.s(44);if(!N(a.node.mode))throw new J.s(54);var b=T(a.node,"x");if(b)throw new J.s(b);J.Ca=a.path},va(){[44].forEach(a=>{J.ja[a]=new J.s(a);J.ja[a].stack="<generic error, no stack>"});J.M=Array(4096);J.C(M,{},"/");J.mkdir("/tmp");J.mkdir("/home");J.mkdir("/home/web_user");sb();tb();J.Ua={MEMFS:M,NODEFS:Q,WORKERFS:S}},ma(a,b,c){J.na=!0;a?J.K("/dev","stdin",a):J.symlink("/dev/tty","/dev/stdin");
b?J.K("/dev","stdout",null,b):J.symlink("/dev/tty","/dev/stdout");c?J.K("/dev","stderr",null,c):J.symlink("/dev/tty1","/dev/stderr");J.open("/dev/stdin",0);J.open("/dev/stdout",1);J.open("/dev/stderr",1)},qb(){J.na=!1;for(var a=0;a<J.streams.length;a++){var b=J.streams[a];b&&J.close(b)}},lb(a,b){try{var c=U(a,{L:!b});a=c.path}catch(g){}var d=!1,f=null;try{c=U(a,{parent:!0}),I(a),c=U(a,{L:!b}),d=!0,f=c.node}catch(g){}return d?f:null},Ba(a,b){a="string"==typeof a?a:V(a);for(b=b.split("/").reverse();b.length;){var c=
b.pop();if(c){var d=H(a+"/"+c);try{J.mkdir(d)}catch(f){}a=d}}return d},ga(a,b,c,d,f,g){var h=b;a&&(a="string"==typeof a?a:V(a),h=b?H(a+"/"+b):a);a=gb(d,f);h=J.create(h,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(f=c.length;d<f;++d)b[d]=c.charCodeAt(d);c=b}J.chmod(h,a|146);b=J.open(h,577);J.write(b,c,0,c.length,0,g);J.close(b);J.chmod(h,a)}},K(a,b,c,d){a=Na("string"==typeof a?a:V(a),b);b=gb(!!c,!!d);J.K.qa||(J.K.qa=64);var f=J.S(J.K.qa++,0);Ya(f,{open(g){g.seekable=!1},close(){d?.buffer?.length&&
d(10)},read(g,h,m,n){for(var q=0,k=0;k<n;k++){try{var r=c()}catch(A){throw new J.s(29);}if(void 0===r&&0===q)throw new J.s(6);if(null===r||void 0===r)break;q++;h[m+k]=r}q&&(g.node.timestamp=Date.now());return q},write(g,h,m,n){for(var q=0;q<n;q++)try{d(h[m+q])}catch(k){throw new J.s(29);}n&&(g.node.timestamp=Date.now());return q}});return rb(a,b,f)},ha(a,b,c,d,f){class g{constructor(){this.ea=!1;this.ba=[];this.wa=void 0;this.xa=this.ya=0}get(k){if(!(k>this.length-1||0>k)){var r=k%this.chunkSize;
return this.wa(k/this.chunkSize|0)[r]}}Ka(k){this.wa=k}za(){var k=new XMLHttpRequest;k.open("HEAD",c,!1);k.send(null);if(!(200<=k.status&&300>k.status||304===k.status))throw Error("Couldn't load "+c+". Status: "+k.status);var r=Number(k.getResponseHeader("Content-length")),A,F=(A=k.getResponseHeader("Accept-Ranges"))&&"bytes"===A;k=(A=k.getResponseHeader("Content-Encoding"))&&"gzip"===A;var y=1048576;F||(y=r);var w=this;w.Ka(W=>{var fa=W*y,X=(W+1)*y-1;X=Math.min(X,r-1);if("undefined"==typeof w.ba[W]){var Jb=
w.ba;if(fa>X)throw Error("invalid range ("+fa+", "+X+") or no bytes requested!");if(X>r-1)throw Error("only "+r+" bytes available! programmer error!");var B=new XMLHttpRequest;B.open("GET",c,!1);r!==y&&B.setRequestHeader("Range","bytes="+fa+"-"+X);B.responseType="arraybuffer";B.overrideMimeType&&B.overrideMimeType("text/plain; charset=x-user-defined");B.send(null);if(!(200<=B.status&&300>B.status||304===B.status))throw Error("Couldn't load "+c+". Status: "+B.status);fa=void 0!==B.response?new Uint8Array(B.response||
[]):Va(B.responseText||"");Jb[W]=fa}if("undefined"==typeof w.ba[W])throw Error("doXHR failed!");return w.ba[W]});if(k||!r)y=r=1,y=r=this.wa(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.ya=r;this.xa=y;this.ea=!0}get length(){this.ea||this.za();return this.ya}get chunkSize(){this.ea||this.za();return this.xa}}if("undefined"!=typeof XMLHttpRequest){if(!l)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";
var h=new g;var m=void 0}else m=c,h=void 0;var n=ub(a,b,d,f);h?n.B=h:m&&(n.B=null,n.url=m);Object.defineProperties(n,{D:{get:function(){return this.B.length}}});var q={};Object.keys(n.A).forEach(k=>{var r=n.A[k];q[k]=(...A)=>{vb(n);return r(...A)}});q.read=(k,r,A,F,y)=>{vb(n);k=k.node.B;if(y>=k.length)r=0;else{F=Math.min(k.length-y,F);if(k.slice)for(var w=0;w<F;w++)r[A+w]=k[y+w];else for(w=0;w<F;w++)r[A+w]=k.get(y+w);r=F}return r};q.T=()=>{vb(n);E();throw new J.s(48);};n.A=q;return n}},Ja=void 0,
wb={},xb=a=>{if(a instanceof Ha||"unwind"==a)return v;ja(1,a)},yb=0,zb=a=>{v=a;0<yb||(qa=!0);ja(a,new Ha(a))},Ab=a=>{v=a;zb(a)},Bb=a=>{if(!qa)try{if(a(),!(0<yb))try{v=a=v,zb(a)}catch(b){xb(b)}}catch(b){xb(b)}},Cb;Cb=()=>performance.now();var Db=J.Ba,Eb=J.ha,Fb=J.K;J.Ra=fb;J.va();e.FS_createPath=J.Ba;e.FS_createDataFile=J.ga;e.FS_createPreloadedFile=J.Ra;e.FS_unlink=J.unlink;e.FS_createLazyFile=J.ha;e.FS_createDevice=J.K;p&&Q.va();
var Hb={m:function(a,b,c){Ja=c;try{var d=Y(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.O.Xa){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var f=G();z[f>>2]=25856;z[f+4>>2]=5;z[f+8>>2]=191;z[f+12>>2]=35387;for(var g=0;32>g;g++)x[f+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.O.Ya)for(f=G(),a=[],g=0;32>g;g++)a.push(x[f+g+17]);return 0;case 21519:if(!d.tty)return-59;
f=G();return z[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:return f=G(),J.oa(d,b,f);case 21523:if(!d.tty)return-59;d.tty.O.Za&&(g=[24,80],f=G(),sa[f>>1]=g[0],sa[f+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof J||"ErrnoError"!==h.name)throw h;return-h.R}},b:function(a,b,c,d){Ja=d;try{b=b?L(ra,b):"";var f=b;if("/"===f.charAt(0))b=f;else{var g=-100===a?J.cwd():Y(a).path;if(0==f.length)throw new J.s(44);b=H(g+
"/"+f)}var h=d?G():0;return J.open(b,c,h).fd}catch(m){if("undefined"==typeof J||"ErrnoError"!==m.name)throw m;return-m.R}},f:()=>{E("")},h:(a,b)=>{Ua(ia||"./this.program",ra,a,b)},k:()=>{yb=0},l:(a,b)=>{wb[a]&&(clearTimeout(wb[a].id),delete wb[a]);if(!b)return 0;var c=setTimeout(()=>{delete wb[a];Bb(()=>Gb(a,Cb()))},b);wb[a]={id:c,rb:b};return 0},g:a=>{var b=ra.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*
Math.ceil(Math.max(a,d)/65536))-pa.buffer.byteLength+65535)/65536;try{pa.grow(d);ua();var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},a:Ab,c:function(a){try{var b=Y(a);J.close(b);return 0}catch(c){if("undefined"==typeof J||"ErrnoError"!==c.name)throw c;return c.R}},e:function(a,b,c,d){try{a:{var f=Y(a);a=b;for(var g,h=b=0;h<c;h++){var m=C[a>>2],n=C[a+4>>2];a+=8;var q=J.read(f,x,m,n,g);if(0>q){var k=-1;break a}b+=q;if(q<n)break;"undefined"!=typeof g&&(g+=q)}k=b}C[d>>2]=k;return 0}catch(r){if("undefined"==
typeof J||"ErrnoError"!==r.name)throw r;return r.R}},i:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var f=Y(a);J.H(f,b,c);ta[d>>3]=BigInt(f.position);f.ka&&0===b&&0===c&&(f.ka=null);return 0}catch(g){if("undefined"==typeof J||"ErrnoError"!==g.name)throw g;return g.R}},d:function(a,b,c,d){try{a:{var f=Y(a);a=b;for(var g,h=b=0;h<c;h++){var m=C[a>>2],n=C[a+4>>2];a+=8;var q=J.write(f,x,m,n,g);if(0>q){var k=-1;break a}b+=q;if(q<n)break;"undefined"!=
typeof g&&(g+=q)}k=b}C[d>>2]=k;return 0}catch(r){if("undefined"==typeof J||"ErrnoError"!==r.name)throw r;return r.R}},j:zb},Z=function(){var a={a:Hb};D++;Da||=e.locateFile?Ca("bspatch.wasm")?"bspatch.wasm":e.locateFile?e.locateFile("bspatch.wasm",t):t+"bspatch.wasm":(new URL("bspatch.wasm",import.meta.url)).href;Ga(a,function(b){Z=b.instance.exports;pa=Z.n;ua();wa.unshift(Z.o);Ba("wasm-instantiate")}).catch(ba);return{}}(),Ib=e._main=(a,b)=>(Ib=e._main=Z.p)(a,b),Gb=(a,b)=>(Gb=Z.r)(a,b),
Kb=a=>(Kb=Z.u)(a);e.addRunDependency=function(){D++};e.removeRunDependency=Ba;e.callMain=Lb;e.ENV={};e.FS_createPreloadedFile=fb;e.FS_unlink=a=>J.unlink(a);e.FS_createPath=Db;e.FS_createDevice=Fb;e.FS=J;e.FS_createDataFile=(a,b,c,d,f,g)=>{J.ga(a,b,c,d,f,g)};e.FS_createLazyFile=Eb;e.NODEFS=Q;e.WORKERFS=S;var Mb;Aa=function Nb(){Mb||Ob();Mb||(Aa=Nb)};
function Lb(a=[]){var b=Ib;a.unshift(ia);var c=a.length,d=Kb(4*(c+1)),f=d;a.forEach(h=>{var m=C,n=f>>2,q=Ta(h)+1,k=Kb(q);Ua(h,ra,k,q);m[n]=k;f+=4});C[f>>2]=0;try{var g=b(c,d);Ab(g,!0);return g}catch(h){return xb(h)}}function Ob(){var a=ha;if(!(0<D)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;){var b=e.preRun.shift();va.unshift(b)}Ia(va);0<D||Mb||(Mb=!0,e.calledRun=!0,qa||(e.noFSInit||J.na||J.ma(),J.la=!1,Ia(wa),Ia(xa),aa(e),Pb&&Lb(a),Ia(ya)))}}var Pb=!1;
e.noInitialRun&&(Pb=!1);Ob();Object.assign(J,{init:J.ma,mkdir:J.mkdir,mount:J.C,chdir:J.chdir,writeFile:J.writeFile,readFile:J.readFile,createLazyFile:J.ha,setIgnorePermissions:function(a){J.la=a}});moduleRtn=ca;


  return moduleRtn;
}
);
})();
export default loadBspatch;
